insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Oklahoma `city`', 'Oklahoma', '`school` #1', 1, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Stamford', 'Connecticut', '`school` #2', 2, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Yakima', 'Washington', '`school` #3', 3, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('New Orleans', 'Louisiana', '`school` #4', 4, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Scottsdale', 'Arizona', '`school` #5', 5, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Fayetteville', 'North Carolina', '`school` #6', 6, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Dallas', 'Texas', '`school` #7', 7, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Roanoke', 'Virginia', '`school` #8', 8, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Washington', '`district` of Columbia', '`school` #9', 9, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Waco', 'Texas', '`school` #10', 10, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Omaha', 'Nebraska', '`school` #11', 11, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Oakland', 'California', '`school` #12', 12, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Colorado Springs', 'Colorado', '`school` #13', 13, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Madison', 'Wisconsin', '`school` #14', 14, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Hartford', 'Connecticut', '`school` #15', 15, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Wichita Falls', 'Texas', '`school` #16', 16, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Richmond', 'Virginia', '`school` #17', 17, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Albany', 'New York', '`school` #18', 18, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Hollywood', 'Florida', '`school` #19', 19, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Montgomery', 'Alabama', '`school` #20', 20, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Corpus Christi', 'Texas', '`school` #21', 21, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Tulsa', 'Oklahoma', '`school` #22', 22, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Atlanta', 'Georgia', '`school` #23', 23, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Jacksonville', 'Florida', '`school` #24', 24, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Atlanta', 'Georgia', '`school` #25', 25, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Brooklyn', 'New York', '`school` #26', 26, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('New York `city`', 'New York', '`school` #27', 27, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Toledo', 'Ohio', '`school` #28', 28, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Omaha', 'Nebraska', '`school` #29', 29, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Fort Wayne', 'Indiana', '`school` #30', 30, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Louisville', 'Kentucky', '`school` #31', 31, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Eugene', 'Oregon', '`school` #32', 32, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Columbus', 'Ohio', '`school` #33', 33, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Sacramento', 'California', '`school` #34', 34, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Valley Forge', 'Pennsylvania', '`school` #35', 35, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Tyler', 'Texas', '`school` #36', 36, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Raleigh', 'North Carolina', '`school` #37', 37, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Miami', 'Florida', '`school` #38', 38, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Austin', 'Texas', '`school` #39', 39, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Birmingham', 'Alabama', '`school` #40', 40, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Atlanta', 'Georgia', '`school` #41', 41, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Lancaster', 'Pennsylvania', '`school` #42', 42, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Springfield', 'Illinois', '`school` #43', 43, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Van Nuys', 'California', '`school` #44', 44, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Salt Lake `city`', 'Utah', '`school` #45', 45, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Springfield', 'Massachusetts', '`school` #46', 46, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Atlanta', 'Georgia', '`school` #47', 47, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Fort Collins', 'Colorado', '`school` #48', 48, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Cleveland', 'Ohio', '`school` #49', 49, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Orlando', 'Florida', '`school` #50', 50, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Washington', '`district` of Columbia', '`school` #51', 51, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Denver', 'Colorado', '`school` #52', 52, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Cincinnati', 'Ohio', '`school` #53', 53, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Van Nuys', 'California', '`school` #54', 54, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Fresno', 'California', '`school` #55', 55, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Aurora', 'Colorado', '`school` #56', 56, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Virginia Beach', 'Virginia', '`school` #57', 57, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Richmond', 'Virginia', '`school` #58', 58, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Detroit', 'Michigan', '`school` #59', 59, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Raleigh', 'North Carolina', '`school` #60', 60, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Tampa', 'Florida', '`school` #61', 61, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Nashville', 'Tennessee', '`school` #62', 62, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('New York `city`', 'New York', '`school` #63', 63, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Baltimore', 'Maryland', '`school` #64', 64, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Shawnee Mission', 'Kansas', '`school` #65', 65, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Louisville', 'Kentucky', '`school` #66', 66, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Oklahoma `city`', 'Oklahoma', '`school` #67', 67, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Philadelphia', 'Pennsylvania', '`school` #68', 68, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('New York `city`', 'New York', '`school` #69', 69, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Charlottesville', 'Virginia', '`school` #70', 70, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Columbus', 'Ohio', '`school` #71', 71, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Houston', 'Texas', '`school` #72', 72, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Saint Cloud', 'Minnesota', '`school` #73', 73, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Indianapolis', 'Indiana', '`school` #74', 74, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Newport Beach', 'California', '`school` #75', 75, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Henderson', 'Nevada', '`school` #76', 76, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Dallas', 'Texas', '`school` #77', 77, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('San Diego', 'California', '`school` #78', 78, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Hyattsville', 'Maryland', '`school` #79', 79, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Sacramento', 'California', '`school` #80', 80, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Louisville', 'Kentucky', '`school` #81', 81, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Brockton', 'Massachusetts', '`school` #82', 82, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Bethlehem', 'Pennsylvania', '`school` #83', 83, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Pittsburgh', 'Pennsylvania', '`school` #84', 84, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Rochester', 'New York', '`school` #85', 85, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Boise', 'Idaho', '`school` #86', 86, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Orlando', 'Florida', '`school` #87', 87, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('New York `city`', 'New York', '`school` #88', 88, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Norwalk', 'Connecticut', '`school` #89', 89, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Chicago', 'Illinois', '`school` #90', 90, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Harrisburg', 'Pennsylvania', '`school` #91', 91, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Tyler', 'Texas', '`school` #92', 92, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Dulles', 'Virginia', '`school` #93', 93, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Cincinnati', 'Ohio', '`school` #94', 94, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Arlington', 'Texas', '`school` #95', 95, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('San Antonio', 'Texas', '`school` #96', 96, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Louisville', 'Kentucky', '`school` #97', 97, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Louisville', 'Kentucky', '`school` #98', 98, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Salt Lake `city`', 'Utah', '`school` #99', 99, 0);
insert into `Entrant` (`city`, `district`, `school`, `User_idUser`, `isBlocked`) values ('Terre Haute', 'Indiana', '`school` #100', 100, 0);
